// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgV5GxSdDdUHNnG5Wuqot_TnyoBBs2ocU',
    appId: '1:1080045481597:web:f1dbf8e061e68ba505cb14',
    messagingSenderId: '1080045481597',
    projectId: 'qarzsiz',
    authDomain: 'qarzsiz.firebaseapp.com',
    storageBucket: 'qarzsiz.appspot.com',
    measurementId: 'G-24J3FL427T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATlrNmHoX6BNTUUmTp6h4Y0dXWcxuAxr4',
    appId: '1:1080045481597:android:a035a5390555148205cb14',
    messagingSenderId: '1080045481597',
    projectId: 'qarzsiz',
    storageBucket: 'qarzsiz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8RyRWc1BnWqAnQBMTBt8laapo9Ioqcgw',
    appId: '1:1080045481597:ios:2f7eb03fce427e8e05cb14',
    messagingSenderId: '1080045481597',
    projectId: 'qarzsiz',
    storageBucket: 'qarzsiz.appspot.com',
    iosBundleId: 'com.example.qarzsiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8RyRWc1BnWqAnQBMTBt8laapo9Ioqcgw',
    appId: '1:1080045481597:ios:c81f6ba5c66058e205cb14',
    messagingSenderId: '1080045481597',
    projectId: 'qarzsiz',
    storageBucket: 'qarzsiz.appspot.com',
    iosBundleId: 'com.example.qarzsiz.RunnerTests',
  );
}
